services:
  - type: web
    name: mental-health-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    plan: free
    
  - type: web
    name: mental-health-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    plan: free
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 