services:
  - type: web
    name: mental-health-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python train_model.py
    startCommand: cd app && uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30 